# Generated by Django 4.2.7 on 2025-05-12 14:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('current_sequence', models.IntegerField(default=1)),
                ('current_state', models.CharField(choices=[('R', 'Resting'), ('B', 'Bored'), ('F', 'Flow'), ('O', 'Overload')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='StateAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('R', 'Resting'), ('B', 'Bored'), ('F', 'Flow'), ('O', 'Overload')], max_length=1)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('difficulty_level', models.IntegerField(default=1)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.testsession')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.CharField(max_length=100)),
                ('correct_answer', models.CharField(max_length=100)),
                ('is_correct', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('state_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.stateattempt')),
            ],
        ),
    ]
